name: go
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  checks:
    name: go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run
      uses: cedrickring/golang-action@1.6.0
            
            
